<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="System.Threading.RateLimiting" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Tests\**" />
    <Content Remove="Tests\**" />
    <EmbeddedResource Remove="Tests\**" />
    <None Remove="Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="HCIExplorer\**" />
    <Content Remove="HCIExplorer\**" />
    <EmbeddedResource Remove="HCIExplorer\**" />
    <None Remove="HCIExplorer\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="EclipseHXSNMP\**" />
    <Content Remove="EclipseHXSNMP\**" />
    <EmbeddedResource Remove="EclipseHXSNMP\**" />
    <None Remove="EclipseHXSNMP\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="HCITestConsole\**" />
    <Content Remove="HCITestConsole\**" />
    <EmbeddedResource Remove="HCITestConsole\**" />
    <None Remove="HCITestConsole\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="RESTLibrary\**" />
    <Content Remove="RESTLibrary\**" />
    <EmbeddedResource Remove="RESTLibrary\**" />
    <None Remove="RESTLibrary\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="RestTestConsole\**" />
    <Content Remove="RestTestConsole\**" />
    <EmbeddedResource Remove="RestTestConsole\**" />
    <None Remove="RestTestConsole\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="BeltpackManager\**" />
    <Content Remove="BeltpackManager\**" />
    <EmbeddedResource Remove="BeltpackManager\**" />
    <None Remove="BeltpackManager\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Program.cs" />
  </ItemGroup>

</Project>
